name: Cron Lighthouse Report Generator

on:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  cron-lighthouse-report-generator:
    name: 'Cron Lighthouse Report Generator'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://web.opentemplatehub.com
          uploadArtifacts: true
          configPath: .github/lighthouserc.yml

      - name: Check for Changes
        run: |
          rm docs/lighthouse/*
          cp .lighthouseci/lhr-*.html docs/lighthouse
          rm .lighthouseci/*

          if git status --porcelain; then
            echo "changes_exist=true" >> $GITHUB_ENV
          else
            echo "changes_exist=false" >> $GITHUB_ENV
          fi

      - name: Git Commit and Push
        if: ${{ env.changes_exist == 'true' }}
        run: |
          git config --global user.email "98660390+oth-service-user@users.noreply.github.com"
          git config --global user.name "OTH Service User"
          git add --all
          git commit -am "Workflow/lighthouse report update"
          git push
